# Enable stateless CSRF protection only for forms that do not rely on the session
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
