---
Name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  ci:
    name: Build & Tests
    runs-on: ubuntu-latest
    env:
      APP_ENV: 'test'
      APP_ENV_NAME: 'test'
      APP_DEBUG: 1
      APP_SECRET: '$ecretf0rt3st'
      SYMFONY_DEPRECATIONS_HELPER: disabled
      DATABASE_URL: 'postgresql://app:password@localhost:3318/app_test?serverVersion=15&charset=utf8'

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_ROOT_PASSWORD: root
          POSTGRES_DB: app_test
          POSTGRES_USER: app
          POSTGRES_PASSWORD: password
          TZ: Europe/Paris
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: composer:v2, flex, pcov, ssh2
          coverage: pcov

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install vendors
        run: composer install --no-progress --ansi --no-scripts

      - name: Validate composer
        run: composer validate --no-check-lock

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node_modules
        id: node-cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.package-lock.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # - name: Npm Install
      #   run: npm install

      # - name: Npm Build
      #   run: npm run build

      # - name: Run PHPUnit tests
      #   run: composer test-with-coverage

      # - name: Monitor coverage
      #   uses: slavcodev/coverage-monitor-action@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     coverage_path: "tests/coverage.xml"
      #     threshold_alert: 60
      #     threshold_warning: 80
      #     threshold_metric: "lines"