name: Optic Deployment

on:
  workflow_run:
    workflows:
      - Optic CI
    types:
      - completed
    branches:
      - prod

permissions:
  contents: read

jobs:
  deployment:
    name: Deployment with VPN
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenVPN and sshpass
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y openvpn sshpass

      - name: Create VPN config and credentials
        run: |
          set -euo pipefail
          echo "${{ secrets.VPN_CONFIG }}" > vpn.conf
          printf "%s\n%s\n" "${{ secrets.VPN_USER }}" "${{ secrets.VPN_PASSWORD }}" > vpn.auth
          sed -i 's|auth-user-pass|auth-user-pass vpn.auth|' vpn.conf
          chmod 600 vpn.conf vpn.auth

      - name: Start VPN
        run: |
          set -euo pipefail
          sudo openvpn --config vpn.conf --daemon
          sleep 10
          ip a  # debug

      - name: Deploy with SSH using password
        run: |
          set -euo pipefail
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" << 'EOF'
            set -euo pipefail
            cd ./Optic-symfony/
            git checkout prod
            git pull --ff-only origin prod
            make deploy
          EOF

      - name: Affichage si le déploiement échoue
        if: failure()
        run: |
          echo ""
          echo " DÉPLOIEMENT ÉCHOUÉ "
          echo "Branche       : ${{ github.event.workflow_run.head_branch }}"
          echo "Auteur        : ${{ github.event.workflow_run.head_commit.author.name }}"
          echo "Voir les logs : ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo ""

      - name: Affichage si le déploiement réussit
        if: success()
        run: |
          echo ""
          echo " DÉPLOIEMENT RÉUSSI "
          echo "Branche       : ${{ github.event.workflow_run.head_branch }}"
          echo "Auteur        : ${{ github.event.workflow_run.head_commit.author.name }}"
          echo "Voir les logs : ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo ""
